version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper

  kafka-create-topics:
    image: confluentinc/cp-kafka:7.3.0
    entrypoint: [ '/bin/sh' ]
    volumes:
      - ./create-topics.sh:/usr/bin/create-topics.sh
    command: create-topics.sh
    depends_on:
      - kafka

  user-service-db:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  user-service:
    build: user-service/
    image: ghcr.io/tony-spark/recipetor-user-service
    environment:
      MONGO_DSN: mongodb://admin:admin@user-service-db:27017/users?authSource=admin
      MONGO_DB: users
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - user-service-db

  ingredient-service-db:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  ingredient-service:
    build: ingredient-service/
    image: ghcr.io/tony-spark/recipetor-ingredient-service
    environment:
      MONGO_DSN: mongodb://admin:admin@ingredient-service-db:27017/ingredients?authSource=admin
      MONGO_DB: ingredients
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - ingredient-service-db

  recipe-service-db:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  recipe-service:
    build: recipe-service/
    image: ghcr.io/tony-spark/recipetor-recipe-service
    environment:
      MONGO_DSN: mongodb://admin:admin@recipe-service-db:27017/recipes?authSource=admin
      MONGO_DB: recipes
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - recipe-service-db

  nutrition-facts-service:
    build: nutrition-facts-service/
    image: ghcr.io/tony-spark/recipetor-nutrition-facts-service