name: integration test

on:
  push:

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start containers
        run: docker-compose up -d --build

      - name: Stop containers
        if: always()
        run: docker-compose down